# Native Windows CMake adapter for a project-local official devkitARM SDK.
# The stock devkitPro CMake entry point requires MSYS CMake; do not modify it.
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR armv6k)
set(NINTENDO_3DS TRUE)
get_filename_component(PROBE_SDK "${CMAKE_CURRENT_LIST_DIR}/../.toolchain/sdk" ABSOLUTE)
set(CMAKE_C_COMPILER "${PROBE_SDK}/devkitARM/bin/arm-none-eabi-gcc.exe")
set(CMAKE_CXX_COMPILER "${PROBE_SDK}/devkitARM/bin/arm-none-eabi-g++.exe")
set(CMAKE_AR "${PROBE_SDK}/devkitARM/bin/arm-none-eabi-gcc-ar.exe")
set(CMAKE_RANLIB "${PROBE_SDK}/devkitARM/bin/arm-none-eabi-gcc-ranlib.exe")
set(CMAKE_EXECUTABLE_SUFFIX .elf)
set(CMAKE_C_FLAGS_INIT "-march=armv6k -mtune=mpcore -mfloat-abi=hard -mtp=soft -mword-relocations -ffunction-sections -fdata-sections -D__3DS__")
set(CMAKE_CXX_FLAGS_INIT "${CMAKE_C_FLAGS_INIT}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-specs=3dsx.specs -L\"${PROBE_SDK}/libctru/lib\" -Wl,--gc-sections")
set(CMAKE_C_STANDARD_INCLUDE_DIRECTORIES "${PROBE_SDK}/libctru/include")
set(CMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES "${PROBE_SDK}/libctru/include")
set(CMAKE_C_STANDARD_LIBRARIES "-lctru -lm" CACHE STRING "" FORCE)
set(CMAKE_CXX_STANDARD_LIBRARIES "-lctru -lm" CACHE STRING "" FORCE)
set(CMAKE_FIND_ROOT_PATH "${PROBE_SDK}/libctru" "${PROBE_SDK}/portlibs/3ds")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set_property(GLOBAL PROPERTY TARGET_SUPPORTS_SHARED_LIBS FALSE)
